name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: Run Playwright tests
      run: npx playwright test
    - name: Commit and push changes
      run: |
        if ! git diff-index --quiet HEAD --; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git stash
          git pull --rebase origin main
          git stash pop
          git add README.md
          git commit -m "docs: Update README.md with latest test results" || echo "No changes to commit"
          git push
        fi
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}